#!/usr/bin/env python3
"""
GCP Picker server — serves gcp_picker.html and handles /run-georeference POST.
Run from ~/atlas-australia/: python3 gcp_server.py
"""
import http.server, json, os, subprocess, sys, threading
from pathlib import Path

DATA = Path.home() / "atlas-australia" / "data"
PORT = 7171

class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, format, *args):
        pass  # suppress access log noise

    def do_POST(self):
        if self.path != '/run-georeference':
            self.send_error(404); return

        length = int(self.headers.get('Content-Length', 0))
        body = json.loads(self.rfile.read(length))
        gcps = body.get('gcps', [])

        if len(gcps) < 6:
            self._json({'ok': False, 'error': 'Need at least 6 GCPs'}); return

        # Write updated georeferencing script
        script = _build_script(gcps)
        script_path = DATA / "_gcp_picker_run.py"
        script_path.write_text(script)

        # Run it in background thread so we can respond first
        def run():
            result = subprocess.run([sys.executable, str(script_path)],
                                    capture_output=True, text=True)
            if result.returncode != 0:
                print("GEOREFERENCE ERROR:\n", result.stderr[-2000:])
            else:
                print("✅ Georeferencing complete!")

        threading.Thread(target=run, daemon=True).start()

        # Give it a second to start, then respond
        import time; time.sleep(1)
        self._json({'ok': True})

    def _json(self, data):
        body = json.dumps(data).encode()
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', len(body))
        self.end_headers()
        self.wfile.write(body)

def _build_script(gcps):
    gcp_lines = "\n".join(
        f"    ({g['px']}, {g['py']}, {g['lon']}, {g['lat']}),"
        for g in gcps
    )
    return f'''#!/usr/bin/env python3
"""Auto-generated by GCP Picker — {len(gcps)} control points"""
import subprocess, os, sys
from pathlib import Path

DATA = Path.home() / "atlas-australia" / "data"
SRC  = str(DATA / "pinkerton_1818_washed.tif")
GCP  = str(DATA / "pinkerton_1818_washed_gcp.tif")
WARP = str(DATA / "pinkerton_1818_washed_wm.tif")
MB   = str(DATA / "historical_pinkerton_1818.mbtiles")
PM   = str(DATA / "historical_pinkerton_1818.pmtiles")

def run(cmd):
    print(f">>> {{' '.join(str(c) for c in cmd)}}")
    r = subprocess.run(cmd)
    if r.returncode != 0:
        print(f"ERROR {{r.returncode}}"); sys.exit(1)

GCPS = [
{gcp_lines}
]

gcp_args = []
for (px, py, lon, lat) in GCPS:
    gcp_args += ["-gcp", str(px), str(py), str(lon), str(lat)]

run(["gdal_translate", "-a_srs", "EPSG:4326", *gcp_args, SRC, GCP])

run(["gdalwarp",
     "-tps", "-s_srs", "EPSG:4326", "-t_srs", "EPSG:3857",
     "-r", "lanczos", "-ts", "8000", "0", "-dstalpha",
     "-te", "12022505", "-5621521", "17478555", "-894010",
     "-co", "TILED=YES", "-co", "COMPRESS=LZW",
     GCP, WARP])

for f in [MB, PM]:
    if os.path.exists(f): os.remove(f)

run(["gdal_translate", "-of", "MBTILES",
     "-co", "TILE_FORMAT=PNG",
     WARP, MB])
run(["gdaladdo", "-r", "average", MB, "2", "4", "8", "16", "32", "64"])
run(["pmtiles", "convert", MB, PM])

size = os.path.getsize(PM)
print(f"\\n✅ Done: {{PM}} — {{size/1e6:.1f}} MB")
print("\\nNow upload:")
print(f"  cd ~/atlas-australia && npx wrangler r2 object put atlas-australia/historical_pinkerton_1818.pmtiles --file=data/historical_pinkerton_1818.pmtiles --remote")
'''

os.chdir(Path.home() / "atlas-australia")
print(f"🗺  GCP Picker server running at http://localhost:{PORT}/gcp_picker.html")
print(f"   Open that URL in your browser, click grid intersections, enter lat/lon.")
print(f"   Ctrl+C to stop.\n")
http.server.HTTPServer(('', PORT), Handler).serve_forever()
