// Atlas map definitions — add new maps here, no code changes needed elsewhere
// Each map may define `sources` (added to MapLibre) and `layers` (MapLibre layer objects)

const MT = import.meta.env.VITE_MAPTILER_KEY;
const R2 = 'https://pub-26caeb1ace954a54baf5c3dc9fdc4fec.r2.dev';

export const ATLAS_MAPS = [
  {
    id: 'states',
    title: 'States & Territories',
    subtitle: 'The political map of Australia',
    story: 'Australia is a federation of six states and two major territories, each with its own government and identity. This map shows the boundaries that divide the continent politically — six states declared at federation in 1901, and two territories carved out over the following decades.',
    palette: {
      background: '#0d1b2a',
      fill: ['#1e4d8c','#2d6a9f','#c0392b','#16a085','#8e44ad','#d35400','#27ae60','#f39c12'],
      stroke: '#ffffff',
      text: '#e8f4f8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [],
    layers: [],  // state fill added dynamically from states.geojson
  },
  {
    id: 'protected-areas',
    title: 'Protected Australia',
    subtitle: 'National parks & protected areas',
    noStateFills: true,
    story: 'Over 22% of Australia\'s landmass is formally protected — a vast network of 14,575 national parks, nature reserves, conservation areas, and Indigenous Protected Areas. This map shows the full CAPAD 2024 dataset. Green tones indicate terrestrial protection; deeper green means stricter protection. Indigenous Protected Areas are shown in gold.',
    palette: {
      background: '#0f1a12',
      fill: ['#1a6b2e'],
      stroke: '#a3e6b0',
      text: '#d4edda',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'protected-areas',
        spec: { type: 'vector', url: `pmtiles://${R2}/capad_2024.pmtiles` },
      },
    ],
    legend: [
      { label: 'National Park',                   layerIds: ['pa-fill-national-park'],   colour: '#1a7a32' },
      { label: 'Nature Reserve & Conservation',   layerIds: ['pa-fill-nature-reserve'],  colour: '#2d9e4f' },
      { label: 'Indigenous Protected Area',       layerIds: ['pa-fill-indigenous'],      colour: '#c8962a' },
      { label: 'Other Protected Areas',           layerIds: ['pa-fill-other'],           colour: '#4aad6e' },
    ],
    layers: [
      {
        id: 'pa-fill-national-park',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['==', ['get', 'TYPE'], 'National Park'],
        paint: { 'fill-color': '#1a7a32', 'fill-opacity': 0.75 },
      },
      {
        id: 'pa-fill-nature-reserve',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['in', ['get', 'TYPE'], ['literal', ['Nature Reserve','Conservation Park','Conservation Area','State Conservation Area','Nature Conservation Reserve']]],
        paint: { 'fill-color': '#2d9e4f', 'fill-opacity': 0.6 },
      },
      {
        id: 'pa-fill-indigenous',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['==', ['get', 'TYPE'], 'Indigenous Protected Area'],
        paint: { 'fill-color': '#c8962a', 'fill-opacity': 0.7 },
      },
      {
        id: 'pa-fill-other',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['!', ['in', ['get', 'TYPE'], ['literal', ['National Park','Nature Reserve','Conservation Park','Conservation Area','State Conservation Area','Nature Conservation Reserve','Indigenous Protected Area']]]],
        paint: { 'fill-color': '#4aad6e', 'fill-opacity': 0.45 },
      },
      {
        id: 'pa-outline',
        type: 'line',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        paint: { 'line-color': '#1a4a22', 'line-width': 0.4, 'line-opacity': 0.5 },
      },
    ],
  },
  {
    id: 'dark',
    title: 'The Dark Continent',
    subtitle: 'Australia at night',
    story: 'A dark canvas reveals the shape of the continent stripped of detail — just coastline, landmass, and silence.',
    palette: {
      background: '#060a0f',
      fill: ['#1a2535'],
      stroke: '#334155',
      text: '#94a3b8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [],
    layers: [],
  },

  // ── Base style showcase ────────────────────────────────────────

  {
    id: 'style-liberty',
    title: 'Liberty',
    subtitle: 'OpenFreeMap — colourful detail',
    story: 'Liberty is OpenFreeMap\'s full-colour style — rich detail, warm tones, and classic OpenStreetMap character. Roads, parks, water, and land use are all colour-coded. A great general-purpose base for data overlays.',
    palette: {
      background: '#f8f4f0',
      fill: ['#c8b89a','#b8c9a3','#e8a87c','#7eb8d4','#c9a0c8','#f4c47a','#90c9a0','#e8c87a'],
      stroke: '#8a7a6a',
      text: '#3a2a1a',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/liberty',
    sources: [],
    layers: [],
  },
  {
    id: 'style-bright',
    title: 'Bright',
    subtitle: 'OpenFreeMap — bold contrast',
    story: 'Bright uses bold, high-contrast colours with strong outlines. Roads pop, water is vivid blue, and land use is clearly delineated. Designed for readability at all zoom levels.',
    palette: {
      background: '#ffffff',
      fill: ['#d4e8f0','#d4f0d4','#f0d4d4','#d4d4f0','#f0e8d4','#d4f0e8','#f0d4e8','#e8f0d4'],
      stroke: '#666666',
      text: '#333333',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/bright',
    sources: [],
    layers: [],
  },

  // ── MapTiler styles ───────────────────────────────────────────

  {
    id: 'style-satellite',
    title: 'Satellite',
    subtitle: 'MapTiler — true colour imagery',
    story: 'True-colour satellite imagery of Australia. Every pixel is real — captured from orbit and stitched into a seamless map. Zoom in to see individual paddocks, reefs, and urban grids from above.',
    palette: { background: '#0a1628', fill: ['#1a3a5c'], stroke: '#4a8ab5', text: '#e0f0ff' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/satellite/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-hybrid',
    title: 'Hybrid',
    subtitle: 'MapTiler — satellite with labels',
    story: 'Satellite imagery overlaid with road networks, place names, and boundaries. The best of both worlds — real-world detail with navigational context.',
    palette: { background: '#0a1628', fill: ['#1a3a5c'], stroke: '#4a8ab5', text: '#e0f0ff' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/hybrid/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-topo',
    title: 'Topographic',
    subtitle: 'MapTiler — elevation & terrain',
    story: 'Topographic contours reveal Australia\'s hidden relief — the vast flat interior, the Great Dividing Range, the dramatic gorges of the Kimberley and Flinders Ranges. Land that looks flat on a standard map tells a different story in topo.',
    palette: { background: '#f5f0e8', fill: ['#e8dfc8'], stroke: '#8a7a5a', text: '#3a2a0a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/topo/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-outdoor',
    title: 'Outdoor',
    subtitle: 'MapTiler — hiking & nature',
    story: 'Designed for the outdoors — hiking trails, national park boundaries, elevation shading, and natural features take centre stage. The map that walkers, climbers, and adventurers reach for.',
    palette: { background: '#f0efe8', fill: ['#dde8cc'], stroke: '#7a9a5a', text: '#2a3a1a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/outdoor-v2/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-aquarelle',
    title: 'Aquarelle',
    subtitle: 'MapTiler — watercolour',
    story: 'Australia rendered as a watercolour painting — soft washes of colour, hand-drawn character, and an artistic warmth that no digital map usually captures. A style unlike any other.',
    palette: { background: '#f8f0e0', fill: ['#e8d8b8'], stroke: '#b8987a', text: '#4a3020' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/aquarelle/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-ocean',
    title: 'Ocean',
    subtitle: 'MapTiler — maritime focus',
    story: 'A nautical-inspired style that brings Australia\'s vast ocean territory into focus. The seas, bays, straits, and reefs surrounding the continent are given equal weight to the land.',
    palette: { background: '#0a2040', fill: ['#1a3a5a'], stroke: '#2a6a9a', text: '#c0e0f0' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/ocean/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-winter',
    title: 'Winter',
    subtitle: 'MapTiler — cool & crisp',
    story: 'A cool, wintry palette — muted blues, soft whites, and crisp outlines. A style that makes the Australian continent feel otherworldly and serene.',
    palette: { background: '#e8f0f8', fill: ['#d0dde8'], stroke: '#7a9ab8', text: '#1a2a3a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/winter/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-toner',
    title: 'Toner',
    subtitle: 'MapTiler — black & white',
    story: 'Stark black and white — every road, river, and coastline reduced to pure ink on paper. A classic newspaper cartography style that strips the map to its bare geometry.',
    palette: { background: '#ffffff', fill: ['#e8e8e8'], stroke: '#000000', text: '#000000' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/toner-v2/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-landscape',
    title: 'Landscape',
    subtitle: 'MapTiler — natural terrain',
    story: 'Natural colour terrain shading — green lowlands, brown highlands, grey mountains. Australia\'s geography rendered the way physical geography textbooks used to draw it.',
    palette: { background: '#e8f0d8', fill: ['#d8e8c8'], stroke: '#8a9a6a', text: '#2a3a1a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/landscape/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-dataviz',
    title: 'Dataviz',
    subtitle: 'MapTiler — clean data canvas',
    story: 'Designed as a neutral backdrop for data overlays — minimal colour, subdued geography, maximum contrast for your data layers. The cartographer\'s equivalent of graph paper.',
    palette: { background: '#f5f5f5', fill: ['#e0e8e8'], stroke: '#9abaaa', text: '#1a2a2a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/dataviz/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-dataviz-dark',
    title: 'Dataviz Dark',
    subtitle: 'MapTiler — dark data canvas',
    story: 'The dark edition of the data visualisation canvas — a near-black base that makes bright data overlays pop with maximum contrast. Ideal for density maps, heat maps, and night-mode dashboards.',
    palette: { background: '#0a1020', fill: ['#1a2535'], stroke: '#2a4a5a', text: '#c0d8e8' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/dataviz-dark/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
];

// Default view — Australia centred, all states visible
export const DEFAULT_VIEW = {
  center: [134.0, -27.0],
  zoom: 4.0,
  minZoom: 3.2,
  maxZoom: 14,
  // Bounding box: cannot pan outside Australia + buffer
  maxBounds: [[105, -48], [160, -7]],
};
