// Atlas map definitions — add new maps here, no code changes needed elsewhere
// Each map may define `sources` (added to MapLibre) and `layers` (MapLibre layer objects)

const MT = import.meta.env.VITE_MAPTILER_KEY;
const R2 = 'https://pub-26caeb1ace954a54baf5c3dc9fdc4fec.r2.dev';

export const ATLAS_MAPS = [
  {
    id: 'states',
    title: 'States & Territories',
    subtitle: 'The political map of Australia',
    story: 'Australia is a federation of six states and two major territories, each with its own government and identity. This map shows the boundaries that divide the continent politically — six states declared at federation in 1901, and two territories carved out over the following decades.',
    palette: {
      background: '#0d1b2a',
      fill: ['#1e4d8c','#2d6a9f','#c0392b','#16a085','#8e44ad','#d35400','#27ae60','#f39c12'],
      stroke: '#ffffff',
      text: '#e8f4f8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [],
    layers: [],  // state fill added dynamically from states.geojson
  },
  {
    id: 'protected-areas',
    title: 'Protected Australia',
    subtitle: 'National parks & protected areas',
    noStateFills: true,
    story: 'Over 22% of Australia\'s landmass is formally protected — a vast network of 14,575 national parks, nature reserves, conservation areas, and Indigenous Protected Areas. This map shows the full CAPAD 2024 dataset. Green tones indicate terrestrial protection; deeper green means stricter protection. Indigenous Protected Areas are shown in gold.',
    palette: {
      background: '#0f1a12',
      fill: ['#1a6b2e'],
      stroke: '#a3e6b0',
      text: '#d4edda',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'protected-areas',
        spec: { type: 'vector', url: `pmtiles://${R2}/capad_2024.pmtiles` },
      },
    ],
    legend: [
      { label: 'National Park',                   layerIds: ['pa-fill-national-park'],   colour: '#1a7a32' },
      { label: 'Nature Reserve & Conservation',   layerIds: ['pa-fill-nature-reserve'],  colour: '#2d9e4f' },
      { label: 'Indigenous Protected Area',       layerIds: ['pa-fill-indigenous'],      colour: '#c8962a' },
      { label: 'Other Protected Areas',           layerIds: ['pa-fill-other'],           colour: '#4aad6e' },
    ],
    layers: [
      {
        id: 'pa-fill-national-park',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['==', ['get', 'TYPE'], 'National Park'],
        paint: { 'fill-color': '#1a7a32', 'fill-opacity': 0.75 },
      },
      {
        id: 'pa-fill-nature-reserve',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['in', ['get', 'TYPE'], ['literal', ['Nature Reserve','Conservation Park','Conservation Area','State Conservation Area','Nature Conservation Reserve']]],
        paint: { 'fill-color': '#2d9e4f', 'fill-opacity': 0.6 },
      },
      {
        id: 'pa-fill-indigenous',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['==', ['get', 'TYPE'], 'Indigenous Protected Area'],
        paint: { 'fill-color': '#c8962a', 'fill-opacity': 0.7 },
      },
      {
        id: 'pa-fill-other',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['!', ['in', ['get', 'TYPE'], ['literal', ['National Park','Nature Reserve','Conservation Park','Conservation Area','State Conservation Area','Nature Conservation Reserve','Indigenous Protected Area']]]],
        paint: { 'fill-color': '#4aad6e', 'fill-opacity': 0.45 },
      },
      {
        id: 'pa-outline',
        type: 'line',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        paint: { 'line-color': '#1a4a22', 'line-width': 0.4, 'line-opacity': 0.5 },
      },
    ],
  },
  {
    id: 'australian-fires',
    title: 'Australian Bushfires',
    subtitle: 'Major fire seasons from 1974 to 2020',
    story: 'Australia has experienced some of the world\'s most devastating wildfires. The 2019–20 Black Summer burnt 18.6 million hectares and killed an estimated 3 billion animals. The 2009 Black Saturday fires killed 173 people in Victoria in a single day. The 1983 Ash Wednesday fires swept through Victoria and South Australia on February 16, killing 75 people. The 2002 WA season was one of the largest in Western Australian history, burning across the Kimberley and Pilbara. The 1974–75 data coverage is limited to southern states — the famous central Australian extent is not captured in available datasets.',
    noStateFills: true,
    initialZoom: 4.0,
    eventSelector: {
      label: 'Select fire season',
      layerPrefix: 'fires',
      events: [
        { id: '2019', label: '2019–20 Black Summer', colour: '#c0392b' },
        { id: '2009', label: '2009 Black Saturday',  colour: '#8e44ad' },
        { id: '1983', label: '1983 Ash Wednesday',   colour: '#e67e22' },
        { id: '2002', label: '2002 WA Season',        colour: '#e74c3c' },
        { id: '1974', label: '1974–75 (incomplete)',  colour: '#f39c12' },
      ],
    },
    palette: {
      background: '#0d0800',
      fill: ['#c0392b'],
      stroke: '#ff6b35',
      text: '#ffd4b8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'fires-2019', spec: { type: 'vector', url: `pmtiles://${R2}/blacksummer_fires.pmtiles` } },
      { id: 'fires-2009', spec: { type: 'vector', url: `pmtiles://${R2}/fires_2009.pmtiles` } },
      { id: 'fires-1983', spec: { type: 'vector', url: `pmtiles://${R2}/fires_1983.pmtiles` } },
      { id: 'fires-2002', spec: { type: 'vector', url: `pmtiles://${R2}/fires_2002.pmtiles` } },
      { id: 'fires-1974', spec: { type: 'vector', url: `pmtiles://${R2}/fires_1974.pmtiles` } },
    ],
    layers: [
      { id: 'fires-2019-fill',    type: 'fill', source: 'fires-2019', 'source-layer': 'fires',
        paint: { 'fill-color': '#c0392b', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-2019-outline', type: 'line', source: 'fires-2019', 'source-layer': 'fires',
        paint: { 'line-color': '#e74c3c', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
      { id: 'fires-2009-fill',    type: 'fill', source: 'fires-2009', 'source-layer': 'fires',
        paint: { 'fill-color': '#8e44ad', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-2009-outline', type: 'line', source: 'fires-2009', 'source-layer': 'fires',
        paint: { 'line-color': '#bd7fcc', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
      { id: 'fires-1983-fill',    type: 'fill', source: 'fires-1983', 'source-layer': 'fires',
        paint: { 'fill-color': '#e67e22', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-1983-outline', type: 'line', source: 'fires-1983', 'source-layer': 'fires',
        paint: { 'line-color': '#f39c12', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
      { id: 'fires-2002-fill',    type: 'fill', source: 'fires-2002', 'source-layer': 'fires',
        paint: { 'fill-color': '#e74c3c', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-2002-outline', type: 'line', source: 'fires-2002', 'source-layer': 'fires',
        paint: { 'line-color': '#ff6b35', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
      { id: 'fires-1974-fill',    type: 'fill', source: 'fires-1974', 'source-layer': 'fires',
        paint: { 'fill-color': '#f39c12', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-1974-outline', type: 'line', source: 'fires-1974', 'source-layer': 'fires',
        paint: { 'line-color': '#f1c40f', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
    ],
  },
  {
    id: 'electoral',
    title: 'Federal Electoral Divisions',
    subtitle: '2022 election results by seat',
    story: 'Australia\'s 150 federal electoral divisions, coloured by the party that won each seat at the May 2022 federal election. Labor (red) won 77 seats to form government under Anthony Albanese. The Coalition (blue) held 58 seats. The Greens (green) won 4 seats. Independents and minor parties (brown) won 11 seats — the largest crossbench in Australian history, driven by the "Teal Independents" in inner-city Liberal heartland. Boundaries are the March 2025 redistribution.',
    noStateFills: true,
    palette: {
      background: '#0d1117',
      fill: ['#e53935'],
      stroke: '#ffffff',
      text: '#f0f0f0',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'electoral', spec: { type: 'vector', url: `pmtiles://${R2}/electoral.pmtiles` } },
    ],
    legend: [
      { label: 'Labor (ALP)',               layerIds: ['elec-labor'],       colour: '#e53935' },
      { label: 'Coalition (Lib/LNP/CLP)',   layerIds: ['elec-coalition'],   colour: '#1565c0' },
      { label: 'Nationals (NP)',            layerIds: ['elec-nationals'],   colour: '#558b2f' },
      { label: 'Greens',                    layerIds: ['elec-greens'],      colour: '#2e7d32' },
      { label: 'Independent / Other',       layerIds: ['elec-other'],       colour: '#795548' },
    ],
    layers: [
      { id: 'elec-labor',     type: 'fill', source: 'electoral', 'source-layer': 'electorates',
        filter: ['==', ['get', 'group'], 'Labor'],
        paint: { 'fill-color': '#e53935', 'fill-opacity': 0.7 } },
      { id: 'elec-coalition', type: 'fill', source: 'electoral', 'source-layer': 'electorates',
        filter: ['==', ['get', 'group'], 'Coalition'],
        paint: { 'fill-color': '#1565c0', 'fill-opacity': 0.7 } },
      { id: 'elec-nationals', type: 'fill', source: 'electoral', 'source-layer': 'electorates',
        filter: ['==', ['get', 'group'], 'Nationals'],
        paint: { 'fill-color': '#558b2f', 'fill-opacity': 0.7 } },
      { id: 'elec-greens',    type: 'fill', source: 'electoral', 'source-layer': 'electorates',
        filter: ['==', ['get', 'group'], 'Greens'],
        paint: { 'fill-color': '#2e7d32', 'fill-opacity': 0.7 } },
      { id: 'elec-other',     type: 'fill', source: 'electoral', 'source-layer': 'electorates',
        filter: ['!in', ['get', 'group'], ['literal', ['Labor','Coalition','Nationals','Greens']]],
        paint: { 'fill-color': '#795548', 'fill-opacity': 0.7 } },
      { id: 'elec-outline',   type: 'line', source: 'electoral', 'source-layer': 'electorates',
        paint: { 'line-color': '#ffffff', 'line-width': 0.5, 'line-opacity': 0.4 } },
    ],
  },
  {
    id: 'renewables',
    title: 'Renewable Energy',
    subtitle: 'Solar and wind farms across Australia',
    story: 'Australia\'s renewable energy build-out mapped from OpenStreetMap. Solar farms (yellow) and wind farms (blue) represent the physical footprints of utility-scale generation — from the massive solar precincts of inland NSW and QLD to the wind corridors of southern Victoria and South Australia. Australia generated over 35% of its electricity from renewables in 2023, with solar capacity doubling every few years. The concentration of solar in the sunbelt and wind along the southern coast reflects both resource availability and grid connection constraints.',
    noStateFills: true,
    palette: {
      background: '#050d1a',
      fill: ['#f9a825'],
      stroke: '#fdd835',
      text: '#fff9c4',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'renewables', spec: { type: 'vector', url: `pmtiles://${R2}/renewables.pmtiles` } },
    ],
    legend: [
      { label: 'Solar farm',  layerIds: ['solar-fill','solar-dot'],  colour: '#f9a825' },
      { label: 'Wind farm',   layerIds: ['wind-fill','wind-dot'],    colour: '#4fc3f7' },
    ],
    layers: [
      { id: 'solar-fill', type: 'fill', source: 'renewables', 'source-layer': 'renewables',
        filter: ['==', ['get', 'kind'], 'solar'],
        paint: { 'fill-color': '#f9a825', 'fill-opacity': 0.75 } },
      { id: 'solar-dot',  type: 'circle', source: 'renewables', 'source-layer': 'renewables',
        filter: ['all', ['==', ['get', 'kind'], 'solar'], ['==', ['geometry-type'], 'Point']],
        paint: { 'circle-radius': 4, 'circle-color': '#f9a825', 'circle-opacity': 0.8 } },
      { id: 'wind-fill',  type: 'fill', source: 'renewables', 'source-layer': 'renewables',
        filter: ['==', ['get', 'kind'], 'wind'],
        paint: { 'fill-color': '#4fc3f7', 'fill-opacity': 0.75 } },
      { id: 'wind-dot',   type: 'circle', source: 'renewables', 'source-layer': 'renewables',
        filter: ['all', ['==', ['get', 'kind'], 'wind'], ['==', ['geometry-type'], 'Point']],
        paint: { 'circle-radius': 4, 'circle-color': '#4fc3f7', 'circle-opacity': 0.8 } },
    ],
  },
  {
    id: 'mines',
    title: 'Mines & Quarries',
    subtitle: 'Active and historic mining operations',
    story: 'Australia is one of the world\'s great mining nations — the largest exporter of iron ore, lithium, coal, and gold. This map shows over 38,000 mine sites and quarries mapped in OpenStreetMap, from the vast open-cut iron ore pits of the Pilbara to gold mines across the goldfields of WA and Victoria, coal mines in the Hunter Valley and Queensland, and quarries scattered across every state. The sheer density of mining tenements in the Pilbara and Queensland\'s resource corridor tells the story of Australia\'s economic backbone.',
    noStateFills: true,
    palette: {
      background: '#0d0a05',
      fill: ['#bf8c30'],
      stroke: '#d4a843',
      text: '#f5e6c8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'mines', spec: { type: 'vector', url: `pmtiles://${R2}/mines.pmtiles` } },
    ],
    legend: [
      { label: 'Mine / industrial site', layerIds: ['mines-fill','mines-dot'], colour: '#bf8c30' },
      { label: 'Quarry',                 layerIds: ['quarry-fill'],            colour: '#8d6e63' },
      { label: 'Historic mine',          layerIds: ['historic-dot'],           colour: '#78909c' },
    ],
    layers: [
      { id: 'quarry-fill',  type: 'fill', source: 'mines', 'source-layer': 'mines',
        filter: ['==', ['get', 'kind'], 'quarry'],
        paint: { 'fill-color': '#8d6e63', 'fill-opacity': 0.7 } },
      { id: 'mines-fill',   type: 'fill', source: 'mines', 'source-layer': 'mines',
        filter: ['!in', ['get', 'kind'], ['literal', ['quarry','mineshaft']]],
        paint: { 'fill-color': '#bf8c30', 'fill-opacity': 0.75 } },
      { id: 'mines-dot',    type: 'circle', source: 'mines', 'source-layer': 'mines',
        filter: ['all', ['==', ['geometry-type'], 'Point'], ['!=', ['get', 'kind'], 'historic']],
        paint: { 'circle-radius': 4, 'circle-color': '#bf8c30', 'circle-opacity': 0.85 } },
      { id: 'historic-dot', type: 'circle', source: 'mines', 'source-layer': 'mines',
        filter: ['all', ['==', ['geometry-type'], 'Point'], ['==', ['get', 'kind'], 'mine']],
        paint: { 'circle-radius': 3, 'circle-color': '#78909c', 'circle-opacity': 0.7 } },
    ],
  },
  {
    id: 'mtb-trails',
    title: 'Mountain Bike Trails',
    subtitle: 'Every mapped MTB trail in Australia',
    story: 'Over 10,600 mountain bike trail segments mapped across Australia from OpenStreetMap. Trails are coloured by the international MTB difficulty scale: green for beginner (scale 0–1), blue for intermediate (scale 2), black for difficult (scale 3), and red for expert and extreme (scale 4–6). Major trail networks include Stromlo (ACT), Derby (TAS), Oakridge (VIC), Bright (VIC), Maydena (TAS), Majura (ACT), Goat Hill (NSW), and many more. Data is community-maintained — coverage is excellent in popular areas, patchy in remote locations.',
    noStateFills: true,
    palette: {
      background: '#0a1205',
      fill: ['#2ecc71'],
      stroke: '#2ecc71',
      text: '#d4f5c4',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'mtb', spec: { type: 'vector', url: `pmtiles://${R2}/mtb_trails.pmtiles` } },
    ],
    legend: [
      { label: 'Green — Beginner (scale 0–1)',    layerIds: ['mtb-green'],  colour: '#27ae60' },
      { label: 'Blue — Intermediate (scale 2)',   layerIds: ['mtb-blue'],   colour: '#2980b9' },
      { label: 'Black — Difficult (scale 3)',     layerIds: ['mtb-black'],  colour: '#bdc3c7' },
      { label: 'Red — Expert / Extreme (4–6)',    layerIds: ['mtb-red'],    colour: '#e74c3c' },
      { label: 'Grey — Unrated trails',           layerIds: ['mtb-grey'],   colour: '#7f8c8d' },
    ],
    layers: [
      {
        id: 'mtb-grey',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['==', ['get', 'mtb_scale'], ''],
        paint: {
          'line-color': '#5a6a5a',
          'line-width': ['interpolate', ['linear'], ['zoom'], 6, 0.8, 10, 1.5, 14, 2.5],
          'line-opacity': 0.6,
        },
      },
      {
        id: 'mtb-green',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['in', ['get', 'mtb_scale'], ['literal', ['0','0+','0-','1','1+','1-','1;0','0;1','Green']]],
        paint: {
          'line-color': '#27ae60',
          'line-width': ['interpolate', ['linear'], ['zoom'], 6, 0.9, 10, 1.8, 14, 3],
          'line-opacity': 0.85,
        },
      },
      {
        id: 'mtb-blue',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['in', ['get', 'mtb_scale'], ['literal', ['2','2+','2-','2;1','1;2','Blue']]],
        paint: {
          'line-color': '#2980b9',
          'line-width': ['interpolate', ['linear'], ['zoom'], 6, 0.9, 10, 1.8, 14, 3],
          'line-opacity': 0.85,
        },
      },
      {
        id: 'mtb-black',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['in', ['get', 'mtb_scale'], ['literal', ['3','3+','Black','Blue / Black']]],
        paint: {
          'line-color': '#bdc3c7',
          'line-width': ['interpolate', ['linear'], ['zoom'], 6, 1, 10, 2, 14, 3.5],
          'line-opacity': 0.9,
        },
      },
      {
        id: 'mtb-red',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['in', ['get', 'mtb_scale'], ['literal', ['4','4+','5','5; 3','6']]],
        paint: {
          'line-color': '#e74c3c',
          'line-width': ['interpolate', ['linear'], ['zoom'], 6, 1, 10, 2, 14, 3.5],
          'line-opacity': 0.95,
        },
      },
    ],
  },
  {
    id: 'australian-floods',
    title: 'Australian Floods',
    subtitle: 'Significant flood events from 1974 to 2022',
    story: 'Flooding is Australia\'s costliest natural hazard. The 2022 South-East Queensland floods inundated large parts of Greater Brisbane in February and March, killing 13 people. The 2011 Queensland floods were the most catastrophic in the state\'s modern history — affecting 75 towns, displacing 200,000 people, and costing $2.4 billion. The 1974 Brisbane River flood remains the benchmark: still the highest recorded flood in Brisbane history, peaking at 6.6 metres at the Brisbane City Gauge. Data covers South-East Queensland only — a national flood extent dataset equivalent to the GA fire mapping does not yet exist.',
    noStateFills: true,
    initialZoom: 5.8,
    initialCenter: [148.5, -26.0],
    eventSelector: {
      label: 'Select flood event',
      layerPrefix: 'floods',
      events: [
        { id: '2022', label: '2022 SE Qld Floods',   colour: '#1a7fc4' },
        { id: '2011', label: '2011 Qld Floods',       colour: '#2196b0' },
        { id: '1974', label: '1974 Brisbane Floods',  colour: '#27ae60' },
      ],
    },
    palette: {
      background: '#060c14',
      fill: ['#1a4a7c'],
      stroke: '#5b9bd5',
      text: '#c8e0f8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'floods-2022', spec: { type: 'vector', url: `pmtiles://${R2}/floods_2022.pmtiles` } },
      { id: 'floods-2011', spec: { type: 'vector', url: `pmtiles://${R2}/floods_2011.pmtiles` } },
      { id: 'floods-1974', spec: { type: 'vector', url: `pmtiles://${R2}/floods_1974.pmtiles` } },
    ],
    layers: [
      { id: 'floods-2022-fill',    type: 'fill', source: 'floods-2022', 'source-layer': 'flood_extent',
        paint: { 'fill-color': '#1a7fc4', 'fill-opacity': 0.55 }, layout: { visibility: 'none' } },
      { id: 'floods-2022-outline', type: 'line', source: 'floods-2022', 'source-layer': 'flood_extent',
        paint: { 'line-color': '#5aabf5', 'line-width': 0.7, 'line-opacity': 0.8 }, layout: { visibility: 'none' } },
      { id: 'floods-2011-fill',    type: 'fill', source: 'floods-2011', 'source-layer': 'flood_extent',
        paint: { 'fill-color': '#2196b0', 'fill-opacity': 0.55 }, layout: { visibility: 'none' } },
      { id: 'floods-2011-outline', type: 'line', source: 'floods-2011', 'source-layer': 'flood_extent',
        paint: { 'line-color': '#56c9e0', 'line-width': 0.7, 'line-opacity': 0.8 }, layout: { visibility: 'none' } },
      { id: 'floods-1974-fill',    type: 'fill', source: 'floods-1974', 'source-layer': 'flood_extent',
        paint: { 'fill-color': '#27ae60', 'fill-opacity': 0.55 }, layout: { visibility: 'none' } },
      { id: 'floods-1974-outline', type: 'line', source: 'floods-1974', 'source-layer': 'flood_extent',
        paint: { 'line-color': '#58d68d', 'line-width': 0.7, 'line-opacity': 0.8 }, layout: { visibility: 'none' } },
    ],
  },
  {
    id: 'dark',
    title: 'The Dark Continent',
    subtitle: 'Australia at night',
    story: 'A dark canvas reveals the shape of the continent stripped of detail — just coastline, landmass, and silence.',
    palette: {
      background: '#060a0f',
      fill: ['#1a2535'],
      stroke: '#334155',
      text: '#94a3b8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [],
    layers: [],
  },

  // ── Base style showcase ────────────────────────────────────────

  {
    id: 'style-liberty',
    title: 'Liberty',
    subtitle: 'OpenFreeMap — colourful detail',
    story: 'Liberty is OpenFreeMap\'s full-colour style — rich detail, warm tones, and classic OpenStreetMap character. Roads, parks, water, and land use are all colour-coded. A great general-purpose base for data overlays.',
    palette: {
      background: '#f8f4f0',
      fill: ['#c8b89a','#b8c9a3','#e8a87c','#7eb8d4','#c9a0c8','#f4c47a','#90c9a0','#e8c87a'],
      stroke: '#8a7a6a',
      text: '#3a2a1a',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/liberty',
    sources: [],
    layers: [],
  },
  {
    id: 'style-bright',
    title: 'Bright',
    subtitle: 'OpenFreeMap — bold contrast',
    story: 'Bright uses bold, high-contrast colours with strong outlines. Roads pop, water is vivid blue, and land use is clearly delineated. Designed for readability at all zoom levels.',
    palette: {
      background: '#ffffff',
      fill: ['#d4e8f0','#d4f0d4','#f0d4d4','#d4d4f0','#f0e8d4','#d4f0e8','#f0d4e8','#e8f0d4'],
      stroke: '#666666',
      text: '#333333',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/bright',
    sources: [],
    layers: [],
  },

  // ── MapTiler styles ───────────────────────────────────────────

  {
    id: 'style-satellite',
    title: 'Satellite',
    subtitle: 'MapTiler — true colour imagery',
    story: 'True-colour satellite imagery of Australia. Every pixel is real — captured from orbit and stitched into a seamless map. Zoom in to see individual paddocks, reefs, and urban grids from above.',
    palette: { background: '#0a1628', fill: ['#1a3a5c'], stroke: '#4a8ab5', text: '#e0f0ff' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/satellite/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-hybrid',
    title: 'Hybrid',
    subtitle: 'MapTiler — satellite with labels',
    story: 'Satellite imagery overlaid with road networks, place names, and boundaries. The best of both worlds — real-world detail with navigational context.',
    palette: { background: '#0a1628', fill: ['#1a3a5c'], stroke: '#4a8ab5', text: '#e0f0ff' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/hybrid/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-topo',
    title: 'Topographic',
    subtitle: 'MapTiler — elevation & terrain',
    story: 'Topographic contours reveal Australia\'s hidden relief — the vast flat interior, the Great Dividing Range, the dramatic gorges of the Kimberley and Flinders Ranges. Land that looks flat on a standard map tells a different story in topo.',
    palette: { background: '#f5f0e8', fill: ['#e8dfc8'], stroke: '#8a7a5a', text: '#3a2a0a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/topo/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-outdoor',
    title: 'Outdoor',
    subtitle: 'MapTiler — hiking & nature',
    story: 'Designed for the outdoors — hiking trails, national park boundaries, elevation shading, and natural features take centre stage. The map that walkers, climbers, and adventurers reach for.',
    palette: { background: '#f0efe8', fill: ['#dde8cc'], stroke: '#7a9a5a', text: '#2a3a1a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/outdoor-v2/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-aquarelle',
    title: 'Aquarelle',
    subtitle: 'MapTiler — watercolour',
    story: 'Australia rendered as a watercolour painting — soft washes of colour, hand-drawn character, and an artistic warmth that no digital map usually captures. A style unlike any other.',
    palette: { background: '#f8f0e0', fill: ['#e8d8b8'], stroke: '#b8987a', text: '#4a3020' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/aquarelle/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-ocean',
    title: 'Ocean',
    subtitle: 'MapTiler — maritime focus',
    story: 'A nautical-inspired style that brings Australia\'s vast ocean territory into focus. The seas, bays, straits, and reefs surrounding the continent are given equal weight to the land.',
    palette: { background: '#0a2040', fill: ['#1a3a5a'], stroke: '#2a6a9a', text: '#c0e0f0' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/ocean/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-winter',
    title: 'Winter',
    subtitle: 'MapTiler — cool & crisp',
    story: 'A cool, wintry palette — muted blues, soft whites, and crisp outlines. A style that makes the Australian continent feel otherworldly and serene.',
    palette: { background: '#e8f0f8', fill: ['#d0dde8'], stroke: '#7a9ab8', text: '#1a2a3a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/winter/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-toner',
    title: 'Toner',
    subtitle: 'MapTiler — black & white',
    story: 'Stark black and white — every road, river, and coastline reduced to pure ink on paper. A classic newspaper cartography style that strips the map to its bare geometry.',
    palette: { background: '#ffffff', fill: ['#e8e8e8'], stroke: '#000000', text: '#000000' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/toner-v2/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-landscape',
    title: 'Landscape',
    subtitle: 'MapTiler — natural terrain',
    story: 'Natural colour terrain shading — green lowlands, brown highlands, grey mountains. Australia\'s geography rendered the way physical geography textbooks used to draw it.',
    palette: { background: '#e8f0d8', fill: ['#d8e8c8'], stroke: '#8a9a6a', text: '#2a3a1a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/landscape/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-dataviz',
    title: 'Dataviz',
    subtitle: 'MapTiler — clean data canvas',
    story: 'Designed as a neutral backdrop for data overlays — minimal colour, subdued geography, maximum contrast for your data layers. The cartographer\'s equivalent of graph paper.',
    palette: { background: '#f5f5f5', fill: ['#e0e8e8'], stroke: '#9abaaa', text: '#1a2a2a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/dataviz/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-dataviz-dark',
    title: 'Dataviz Dark',
    subtitle: 'MapTiler — dark data canvas',
    story: 'The dark edition of the data visualisation canvas — a near-black base that makes bright data overlays pop with maximum contrast. Ideal for density maps, heat maps, and night-mode dashboards.',
    palette: { background: '#0a1020', fill: ['#1a2535'], stroke: '#2a4a5a', text: '#c0d8e8' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/dataviz-dark/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
];

// Default view — Australia centred, all states visible
export const DEFAULT_VIEW = {
  center: [134.0, -27.0],
  zoom: 4.0,
  minZoom: 3.2,
  maxZoom: 14,
  // Bounding box: cannot pan outside Australia + buffer
  maxBounds: [[105, -48], [160, -7]],
};
