// Atlas map definitions — add new maps here, no code changes needed elsewhere
// Each map may define `sources` (added to MapLibre) and `layers` (MapLibre layer objects)

const MT = import.meta.env.VITE_MAPTILER_KEY;
const R2 = 'https://pub-26caeb1ace954a54baf5c3dc9fdc4fec.r2.dev';

export const ATLAS_MAPS = [
  {
    id: 'states',
    category: 'base',
    title: 'States & Territories',
    subtitle: 'The political map of Australia',
    story: 'Australia is a federation of six states and two major territories, each with its own government and identity. This map shows the boundaries that divide the continent politically — six states declared at federation in 1901, and two territories carved out over the following decades.',
    palette: {
      background: '#0d1b2a',
      fill: ['#1e4d8c','#2d6a9f','#c0392b','#16a085','#8e44ad','#d35400','#27ae60','#f39c12'],
      stroke: '#ffffff',
      text: '#e8f4f8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [],
    layers: [],  // state fill added dynamically from states.geojson
  },
  {
    id: 'protected-areas',
    category: 'environment',
    title: 'Protected Australia',
    subtitle: 'National parks & protected areas',
    noStateFills: true,
    story: 'Over 22% of Australia\'s landmass is formally protected — a vast network of 14,575 national parks, nature reserves, conservation areas, and Indigenous Protected Areas. This map shows the full CAPAD 2024 dataset. Green tones indicate terrestrial protection; deeper green means stricter protection. Indigenous Protected Areas are shown in gold.',
    palette: {
      background: '#0f1a12',
      fill: ['#1a6b2e'],
      stroke: '#a3e6b0',
      text: '#d4edda',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'protected-areas',
        spec: { type: 'vector', url: `pmtiles://${R2}/capad_2024.pmtiles` },
      },
    ],
    legend: [
      { label: 'National Park',                   layerIds: ['pa-fill-national-park'],   colour: '#1a7a32' },
      { label: 'Nature Reserve & Conservation',   layerIds: ['pa-fill-nature-reserve'],  colour: '#2d9e4f' },
      { label: 'Indigenous Protected Area',       layerIds: ['pa-fill-indigenous'],      colour: '#c8962a' },
      { label: 'Other Protected Areas',           layerIds: ['pa-fill-other'],           colour: '#4aad6e' },
    ],
    layers: [
      {
        id: 'pa-fill-national-park',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['==', ['get', 'TYPE'], 'National Park'],
        paint: { 'fill-color': '#1a7a32', 'fill-opacity': 0.75 },
      },
      {
        id: 'pa-fill-nature-reserve',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['in', ['get', 'TYPE'], ['literal', ['Nature Reserve','Conservation Park','Conservation Area','State Conservation Area','Nature Conservation Reserve']]],
        paint: { 'fill-color': '#2d9e4f', 'fill-opacity': 0.6 },
      },
      {
        id: 'pa-fill-indigenous',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['==', ['get', 'TYPE'], 'Indigenous Protected Area'],
        paint: { 'fill-color': '#c8962a', 'fill-opacity': 0.7 },
      },
      {
        id: 'pa-fill-other',
        type: 'fill',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        filter: ['!', ['in', ['get', 'TYPE'], ['literal', ['National Park','Nature Reserve','Conservation Park','Conservation Area','State Conservation Area','Nature Conservation Reserve','Indigenous Protected Area']]]],
        paint: { 'fill-color': '#4aad6e', 'fill-opacity': 0.45 },
      },
      {
        id: 'pa-outline',
        type: 'line',
        source: 'protected-areas',
        'source-layer': 'protected_areas',
        paint: { 'line-color': '#1a4a22', 'line-width': 0.4, 'line-opacity': 0.5 },
      },
    ],
  },
  {
    id: 'australian-fires',
    category: 'disasters',
    title: 'Australian Bushfires',
    subtitle: 'Major fire seasons from 1974 to 2020',
    story: 'Australia has experienced some of the world\'s most devastating wildfires. The 2019–20 Black Summer burnt 18.6 million hectares and killed an estimated 3 billion animals. The 2009 Black Saturday fires killed 173 people in Victoria in a single day. The 1983 Ash Wednesday fires swept through Victoria and South Australia on February 16, killing 75 people. The 2002 WA season was one of the largest in Western Australian history, burning across the Kimberley and Pilbara. The 1974–75 data coverage is limited to southern states — the famous central Australian extent is not captured in available datasets.',
    noStateFills: true,
    initialZoom: 4.0,
    eventSelector: {
      label: 'Select fire season',
      layerPrefix: 'fires',
      events: [
        { id: '2019', label: '2019–20 Black Summer', colour: '#c0392b' },
        { id: '2009', label: '2009 Black Saturday',  colour: '#8e44ad' },
        { id: '1983', label: '1983 Ash Wednesday',   colour: '#e67e22' },
        { id: '2002', label: '2002 WA Season',        colour: '#e74c3c' },
        { id: '1974', label: '1974–75 (incomplete)',  colour: '#f39c12' },
      ],
    },
    palette: {
      background: '#0d0800',
      fill: ['#c0392b'],
      stroke: '#ff6b35',
      text: '#ffd4b8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'fires-2019', spec: { type: 'vector', url: `pmtiles://${R2}/blacksummer_fires.pmtiles` } },
      { id: 'fires-2009', spec: { type: 'vector', url: `pmtiles://${R2}/fires_2009.pmtiles` } },
      { id: 'fires-1983', spec: { type: 'vector', url: `pmtiles://${R2}/fires_1983.pmtiles` } },
      { id: 'fires-2002', spec: { type: 'vector', url: `pmtiles://${R2}/fires_2002.pmtiles` } },
      { id: 'fires-1974', spec: { type: 'vector', url: `pmtiles://${R2}/fires_1974.pmtiles` } },
    ],
    layers: [
      { id: 'fires-2019-fill',    type: 'fill', source: 'fires-2019', 'source-layer': 'fires',
        paint: { 'fill-color': '#c0392b', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-2019-outline', type: 'line', source: 'fires-2019', 'source-layer': 'fires',
        paint: { 'line-color': '#e74c3c', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
      { id: 'fires-2009-fill',    type: 'fill', source: 'fires-2009', 'source-layer': 'fires',
        paint: { 'fill-color': '#8e44ad', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-2009-outline', type: 'line', source: 'fires-2009', 'source-layer': 'fires',
        paint: { 'line-color': '#bd7fcc', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
      { id: 'fires-1983-fill',    type: 'fill', source: 'fires-1983', 'source-layer': 'fires',
        paint: { 'fill-color': '#e67e22', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-1983-outline', type: 'line', source: 'fires-1983', 'source-layer': 'fires',
        paint: { 'line-color': '#f39c12', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
      { id: 'fires-2002-fill',    type: 'fill', source: 'fires-2002', 'source-layer': 'fires',
        paint: { 'fill-color': '#e74c3c', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-2002-outline', type: 'line', source: 'fires-2002', 'source-layer': 'fires',
        paint: { 'line-color': '#ff6b35', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
      { id: 'fires-1974-fill',    type: 'fill', source: 'fires-1974', 'source-layer': 'fires',
        paint: { 'fill-color': '#f39c12', 'fill-opacity': 0.65 }, layout: { visibility: 'none' } },
      { id: 'fires-1974-outline', type: 'line', source: 'fires-1974', 'source-layer': 'fires',
        paint: { 'line-color': '#f1c40f', 'line-width': 0.6, 'line-opacity': 0.7 }, layout: { visibility: 'none' } },
    ],
  },
  {
    id: 'electoral',
    category: 'society',
    title: 'Federal Electoral Divisions',
    subtitle: '2022 election results by seat',
    story: 'Australia\'s 150 federal electoral divisions, coloured by the party that won each seat at the May 2022 federal election. Labor (red) won 77 seats to form government under Anthony Albanese. The Coalition (blue) held 58 seats. The Greens (green) won 4 seats. Independents and minor parties (brown) won 11 seats — the largest crossbench in Australian history, driven by the "Teal Independents" in inner-city Liberal heartland. Boundaries are the March 2025 redistribution.',
    noStateFills: true,
    palette: {
      background: '#0d1117',
      fill: ['#e53935'],
      stroke: '#ffffff',
      text: '#f0f0f0',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'electoral', spec: { type: 'vector', url: `pmtiles://${R2}/electoral.pmtiles` } },
    ],
    legend: [
      { label: 'Labor (ALP)',               layerIds: ['elec-fill'], colour: '#e53935' },
      { label: 'Coalition (Lib/LNP/CLP)',   layerIds: ['elec-fill'], colour: '#1565c0' },
      { label: 'Nationals (NP)',            layerIds: ['elec-fill'], colour: '#558b2f' },
      { label: 'Greens',                    layerIds: ['elec-fill'], colour: '#2e7d32' },
      { label: 'Independent / Other',       layerIds: ['elec-fill'], colour: '#795548' },
    ],
    layers: [
      { id: 'elec-fill', type: 'fill', source: 'electoral', 'source-layer': 'electorates',
        paint: {
          'fill-color': ['match', ['get', 'group'],
            'Labor',     '#e53935',
            'Coalition', '#1565c0',
            'Nationals', '#558b2f',
            'Greens',    '#2e7d32',
            /* default */ '#795548',
          ],
          'fill-opacity': 0.7,
        } },
      { id: 'elec-outline', type: 'line', source: 'electoral', 'source-layer': 'electorates',
        paint: { 'line-color': '#ffffff', 'line-width': 0.5, 'line-opacity': 0.4 } },
    ],
  },
  {
    id: 'renewables',
    category: 'society',
    title: 'Renewable Energy',
    subtitle: 'Solar and wind farms across Australia',
    story: 'Australia\'s renewable energy build-out mapped from OpenStreetMap. Solar farms (yellow) and wind farms (blue) represent the physical footprints of utility-scale generation — from the massive solar precincts of inland NSW and QLD to the wind corridors of southern Victoria and South Australia. Australia generated over 35% of its electricity from renewables in 2023, with solar capacity doubling every few years. The concentration of solar in the sunbelt and wind along the southern coast reflects both resource availability and grid connection constraints.',
    noStateFills: true,
    palette: {
      background: '#050d1a',
      fill: ['#f9a825'],
      stroke: '#fdd835',
      text: '#fff9c4',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'renewables', spec: { type: 'vector', url: `pmtiles://${R2}/renewables.pmtiles` } },
    ],
    legend: [
      { label: 'Solar farm',  layerIds: ['solar-fill','solar-dot'],  colour: '#f9a825' },
      { label: 'Wind farm',   layerIds: ['wind-fill','wind-dot'],    colour: '#4fc3f7' },
    ],
    layers: [
      { id: 'solar-fill', type: 'fill', source: 'renewables', 'source-layer': 'renewables',
        filter: ['==', ['get', 'kind'], 'solar'],
        paint: { 'fill-color': '#f9a825', 'fill-opacity': 0.75 } },
      { id: 'solar-dot',  type: 'circle', source: 'renewables', 'source-layer': 'renewables',
        filter: ['all', ['==', ['get', 'kind'], 'solar'], ['==', ['geometry-type'], 'Point']],
        paint: { 'circle-radius': ['interpolate',['linear'],['zoom'], 4,7, 7,5, 14,3], 'circle-color': '#f9a825', 'circle-opacity': 0.85 } },
      { id: 'wind-fill',  type: 'fill', source: 'renewables', 'source-layer': 'renewables',
        filter: ['==', ['get', 'kind'], 'wind'],
        paint: { 'fill-color': '#4fc3f7', 'fill-opacity': 0.75 } },
      { id: 'wind-dot',   type: 'circle', source: 'renewables', 'source-layer': 'renewables',
        filter: ['all', ['==', ['get', 'kind'], 'wind'], ['==', ['geometry-type'], 'Point']],
        paint: { 'circle-radius': ['interpolate',['linear'],['zoom'], 4,7, 7,5, 14,3], 'circle-color': '#4fc3f7', 'circle-opacity': 0.85 } },
    ],
  },
  {
    id: 'mines',
    category: 'society',
    title: 'Mines & Quarries',
    subtitle: 'Active and historic mining operations',
    story: 'Australia is one of the world\'s great mining nations — the largest exporter of iron ore, lithium, coal, and gold. This map shows over 38,000 mine sites and quarries mapped in OpenStreetMap, from the vast open-cut iron ore pits of the Pilbara to gold mines across the goldfields of WA and Victoria, coal mines in the Hunter Valley and Queensland, and quarries scattered across every state. The sheer density of mining tenements in the Pilbara and Queensland\'s resource corridor tells the story of Australia\'s economic backbone.',
    noStateFills: true,
    palette: {
      background: '#0d0a05',
      fill: ['#bf8c30'],
      stroke: '#d4a843',
      text: '#f5e6c8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'mines', spec: { type: 'vector', url: `pmtiles://${R2}/mines.pmtiles` } },
    ],
    legend: [
      { label: 'Mine / industrial site', layerIds: ['mines-fill','mines-dot'], colour: '#bf8c30' },
      { label: 'Quarry',                 layerIds: ['quarry-fill'],            colour: '#8d6e63' },
    ],
    layers: [
      { id: 'quarry-fill',  type: 'fill', source: 'mines', 'source-layer': 'mines',
        filter: ['==', ['get', 'kind'], 'quarry'],
        paint: { 'fill-color': '#8d6e63', 'fill-opacity': 0.7 } },
      { id: 'mines-fill',   type: 'fill', source: 'mines', 'source-layer': 'mines',
        filter: ['match', ['get', 'kind'], ['quarry','mineshaft'], false, true],
        paint: { 'fill-color': '#bf8c30', 'fill-opacity': 0.75 } },
      { id: 'mines-dot',    type: 'circle', source: 'mines', 'source-layer': 'mines',
        filter: ['==', ['geometry-type'], 'Point'],
        paint: { 'circle-radius': ['interpolate',['linear'],['zoom'], 4,7, 7,5, 14,3], 'circle-color': '#bf8c30', 'circle-opacity': 0.85 } },
    ],
  },
  {
    id: 'population',
    category: 'society',
    title: 'Population Density',
    subtitle: '2021 Census — people per km²',
    story: 'Australia is one of the world\'s least densely populated countries — 26 million people spread across 7.7 million km², with the vast majority hugging the coastline. This map shows population density by Statistical Area Level 2 (SA2) from the 2021 ABS Census. The concentration in Sydney, Melbourne, Brisbane, Perth and Adelaide is stark: 80% of Australians live within 50km of the coast. The outback interior, which covers 70% of the country\'s land area, holds less than 5% of the population. Colour scale is logarithmic — each band represents a 10× increase in density.',
    noStateFills: true,
    palette: {
      background: '#0a0f1a',
      fill: ['#08306b'],
      stroke: '#2171b5',
      text: '#c6dbef',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'population', spec: { type: 'vector', url: `pmtiles://${R2}/population.pmtiles` } },
    ],
    legend: [
      { label: '< 1 p/km²  (outback)',       colour: '#f7fbff' },
      { label: '1 – 10',                       colour: '#c6dbef' },
      { label: '10 – 50',                      colour: '#6baed6' },
      { label: '50 – 200',                     colour: '#2171b5' },
      { label: '200 – 1,000',                  colour: '#08519c' },
      { label: '1,000 – 5,000',               colour: '#08306b' },
      { label: '> 5,000  (inner city)',        colour: '#ffffff' },
    ],
    layers: [
      { id: 'pop-fill', type: 'fill', source: 'population', 'source-layer': 'population',
        paint: {
          'fill-color': ['step', ['get', 'density'],
            '#f7fbff',
            1,    '#c6dbef',
            10,   '#6baed6',
            50,   '#2171b5',
            200,  '#08519c',
            1000, '#08306b',
            5000, '#ffffff',
          ],
          'fill-opacity': 0.85,
        },
      },
      { id: 'pop-outline', type: 'line', source: 'population', 'source-layer': 'population',
        paint: { 'line-color': '#1a2a3a', 'line-width': 0.3, 'line-opacity': 0.5 },
      },
    ],
  },
  {
    id: 'land-access',
    category: 'environment',
    title: 'Land Access',
    subtitle: 'Protected, forest, farmland & urban — who owns Australia',
    story: 'Land access across Australia mapped from OpenStreetMap — where community contributors have tagged land use, tenure, and access. Protected areas (national parks, reserves, conservation areas) are shown in dark green. Publicly accessible forests and crown land in mid-green. Farmland and pastoral areas in tan. Urban and built-up areas in orange. Coverage is excellent in populated regions — zoom in to see individual streets and parcels. Remote and rural areas may be sparse where OSM contributors haven\'t yet mapped land tenure. Data is community-maintained and does not represent legal tenure boundaries.',
    noStateFills: true,
    palette: {
      background: '#f5f0e8',
      fill: ['#2d6a4f'],
      stroke: '#2d6a4f',
      text: '#2d3a2e',
    },
    legend: [
      { label: 'Protected (National Parks & Reserves)', layerIds: ['landaccess-protected'], colour: '#2d6a4f' },
      { label: 'Forest, Crown Land & Native Grazing',  layerIds: ['landaccess-forest'],    colour: '#52b788' },
      { label: 'Farmland (Crops & Pastoral)',          layerIds: ['landaccess-farmland'],  colour: '#c8a96e' },
      { label: 'Urban & Built-up',                     layerIds: ['landaccess-urban'],     colour: '#bf6030' },
    ],
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      { id: 'landaccess', spec: { type: 'vector', url: `pmtiles://${R2}/landaccess.pmtiles` } },
    ],
    layers: [
      {
        id: 'landaccess-protected',
        type: 'fill',
        source: 'landaccess',
        'source-layer': 'landaccess',
        filter: ['==', ['get', 'category'], 'protected'],
        paint: {
          'fill-color': '#2d6a4f',
          'fill-opacity': 0.75,
        },
      },
      {
        id: 'landaccess-forest',
        type: 'fill',
        source: 'landaccess',
        'source-layer': 'landaccess',
        filter: ['==', ['get', 'category'], 'forest'],
        paint: { 'fill-color': '#52b788', 'fill-opacity': 0.75 },
      },
      {
        id: 'landaccess-farmland',
        type: 'fill',
        source: 'landaccess',
        'source-layer': 'landaccess',
        filter: ['==', ['get', 'category'], 'farmland'],
        paint: { 'fill-color': '#c8a96e', 'fill-opacity': 0.65 },
      },
      {
        id: 'landaccess-urban',
        type: 'fill',
        source: 'landaccess',
        'source-layer': 'landaccess',
        filter: ['==', ['get', 'category'], 'urban'],
        paint: {
          'fill-color': '#bf6030',
          'fill-opacity': 0.75,
        },
      },
    ],
  },
  {
    id: 'mtb-trails',
    category: 'society',
    title: 'Mountain Bike Trails',
    subtitle: 'Every mapped MTB trail in Australia',
    story: 'Over 10,600 mountain bike trail segments mapped across Australia from OpenStreetMap. Trails are coloured by the international MTB difficulty scale: green for beginner (scale 0–1), blue for intermediate (scale 2), black for difficult (scale 3), and red for expert and extreme (scale 4–6). Major trail networks include Stromlo (ACT), Derby (TAS), Oakridge (VIC), Bright (VIC), Maydena (TAS), Majura (ACT), Goat Hill (NSW), and many more. Data is community-maintained — coverage is excellent in popular areas, patchy in remote locations.',
    noStateFills: true,
    palette: {
      background: '#0a1205',
      fill: ['#2ecc71'],
      stroke: '#2ecc71',
      text: '#d4f5c4',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'mtb', spec: { type: 'vector', url: `pmtiles://${R2}/mtb_trails.pmtiles` } },
    ],
    legend: [
      { label: 'Green — Beginner (scale 0–1)',    layerIds: ['mtb-green'],  colour: '#27ae60' },
      { label: 'Blue — Intermediate (scale 2)',   layerIds: ['mtb-blue'],   colour: '#2980b9' },
      { label: 'Black — Difficult (scale 3)',     layerIds: ['mtb-black'],  colour: '#bdc3c7' },
      { label: 'Red — Expert / Extreme (4–6)',    layerIds: ['mtb-red'],    colour: '#e74c3c' },
      { label: 'Grey — Unrated trails',           layerIds: ['mtb-grey'],   colour: '#7f8c8d' },
    ],
    layers: [
      {
        id: 'mtb-grey',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['==', ['get', 'mtb_scale'], ''],
        paint: {
          'line-color': '#5a6a5a',
          'line-width': ['interpolate', ['linear'], ['zoom'], 4, 2, 6, 1.2, 10, 1.5, 14, 2.5],
          'line-opacity': 0.6,
        },
      },
      {
        id: 'mtb-green',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['in', ['get', 'mtb_scale'], ['literal', ['0','0+','0-','1','1+','1-','1;0','0;1','Green']]],
        paint: {
          'line-color': '#27ae60',
          'line-width': ['interpolate', ['linear'], ['zoom'], 4, 2.5, 6, 1.2, 10, 1.8, 14, 3],
          'line-opacity': 0.85,
        },
      },
      {
        id: 'mtb-blue',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['in', ['get', 'mtb_scale'], ['literal', ['2','2+','2-','2;1','1;2','Blue']]],
        paint: {
          'line-color': '#2980b9',
          'line-width': ['interpolate', ['linear'], ['zoom'], 4, 2.5, 6, 1.2, 10, 1.8, 14, 3],
          'line-opacity': 0.85,
        },
      },
      {
        id: 'mtb-black',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['in', ['get', 'mtb_scale'], ['literal', ['3','3+','Black','Blue / Black']]],
        paint: {
          'line-color': '#bdc3c7',
          'line-width': ['interpolate', ['linear'], ['zoom'], 4, 2.5, 6, 1.2, 10, 2, 14, 3.5],
          'line-opacity': 0.9,
        },
      },
      {
        id: 'mtb-red',
        type: 'line',
        source: 'mtb',
        'source-layer': 'mtb_trails',
        filter: ['in', ['get', 'mtb_scale'], ['literal', ['4','4+','5','5; 3','6']]],
        paint: {
          'line-color': '#e74c3c',
          'line-width': ['interpolate', ['linear'], ['zoom'], 4, 2.5, 6, 1.2, 10, 2, 14, 3.5],
          'line-opacity': 0.95,
        },
      },
    ],
  },
  {
    id: 'australian-floods',
    category: 'disasters',
    title: 'Australian Floods',
    subtitle: 'Significant flood events from 1974 to 2022',
    story: 'Flooding is Australia\'s costliest natural hazard. The 2022 South-East Queensland floods inundated large parts of Greater Brisbane in February and March, killing 13 people. The 2011 Queensland floods were the most catastrophic in the state\'s modern history — affecting 75 towns, displacing 200,000 people, and costing $2.4 billion. The 1974 Brisbane River flood remains the benchmark: still the highest recorded flood in Brisbane history, peaking at 6.6 metres at the Brisbane City Gauge. Data covers South-East Queensland only — a national flood extent dataset equivalent to the GA fire mapping does not yet exist.',
    noStateFills: true,
    initialZoom: 5.8,
    initialCenter: [148.5, -26.0],
    eventSelector: {
      label: 'Select flood event',
      layerPrefix: 'floods',
      events: [
        { id: '2022', label: '2022 SE Qld Floods',   colour: '#1a7fc4' },
        { id: '2011', label: '2011 Qld Floods',       colour: '#2196b0' },
        { id: '1974', label: '1974 Brisbane Floods',  colour: '#27ae60' },
      ],
    },
    palette: {
      background: '#060c14',
      fill: ['#1a4a7c'],
      stroke: '#5b9bd5',
      text: '#c8e0f8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [
      { id: 'floods-2022', spec: { type: 'vector', url: `pmtiles://${R2}/floods_2022.pmtiles` } },
      { id: 'floods-2011', spec: { type: 'vector', url: `pmtiles://${R2}/floods_2011.pmtiles` } },
      { id: 'floods-1974', spec: { type: 'vector', url: `pmtiles://${R2}/floods_1974.pmtiles` } },
    ],
    layers: [
      { id: 'floods-2022-fill',    type: 'fill', source: 'floods-2022', 'source-layer': 'flood_extent',
        paint: { 'fill-color': '#1a7fc4', 'fill-opacity': 0.55 }, layout: { visibility: 'none' } },
      { id: 'floods-2022-outline', type: 'line', source: 'floods-2022', 'source-layer': 'flood_extent',
        paint: { 'line-color': '#5aabf5', 'line-width': 0.7, 'line-opacity': 0.8 }, layout: { visibility: 'none' } },
      { id: 'floods-2011-fill',    type: 'fill', source: 'floods-2011', 'source-layer': 'flood_extent',
        paint: { 'fill-color': '#2196b0', 'fill-opacity': 0.55 }, layout: { visibility: 'none' } },
      { id: 'floods-2011-outline', type: 'line', source: 'floods-2011', 'source-layer': 'flood_extent',
        paint: { 'line-color': '#56c9e0', 'line-width': 0.7, 'line-opacity': 0.8 }, layout: { visibility: 'none' } },
      { id: 'floods-1974-fill',    type: 'fill', source: 'floods-1974', 'source-layer': 'flood_extent',
        paint: { 'fill-color': '#27ae60', 'fill-opacity': 0.55 }, layout: { visibility: 'none' } },
      { id: 'floods-1974-outline', type: 'line', source: 'floods-1974', 'source-layer': 'flood_extent',
        paint: { 'line-color': '#58d68d', 'line-width': 0.7, 'line-opacity': 0.8 }, layout: { visibility: 'none' } },
    ],
  },
  {
    id: 'dark',
    category: 'base',
    title: 'The Dark Continent',
    subtitle: 'Australia at night',
    story: 'A dark canvas reveals the shape of the continent stripped of detail — just coastline, landmass, and silence.',
    palette: {
      background: '#060a0f',
      fill: ['#1a2535'],
      stroke: '#334155',
      text: '#94a3b8',
    },
    baseStyle: 'https://tiles.openfreemap.org/styles/dark',
    sources: [],
    layers: [],
  },

  // ── Historical maps ────────────────────────────────────────────

  {
    id: 'historical-arrowsmith-1844',
    category: 'historical',
    title: 'Arrowsmith 1844',
    subtitle: 'Colonial survey of Australia',
    story: 'John Arrowsmith\u2019s 1844 map of Australia \u2014 drawn in London from the surveys of Matthew Flinders, Nicolas Baudin, and the British Admiralty. It captures the continent as British colonists understood it: the settled coasts mapped in meticulous detail, the interior almost entirely blank. Only five years since the first overland crossing of southern Australia by Edward John Eyre. Perth, Adelaide, Melbourne, Sydney, and Hobart are marked; Darwin, Alice Springs, and most of Queensland do not yet exist. The map is a portrait of a continent still being written.',
    palette: {
      background: '#f5f0e8',
      fill: ['#c8a878'],
      stroke: '#7a6040',
      text: '#3a2a10',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-arrowsmith',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_arrowsmith.pmtiles`,
          tileSize: 256,
          maxzoom: 8,
        },
      },
    ],
    layers: [
      {
        id: 'historical-arrowsmith-layer',
        type: 'raster',
        source: 'historical-arrowsmith',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-thomson-1814',
    category: 'historical',
    title: 'Thomson 1814',
    subtitle: 'First map named \u201cAustralia\u201d',
    story: 'John Thomson\u2019s 1814 map of Australia, New Zealand and New Guinea was among the first major English atlases to adopt Matthew Flinders\u2019 proposed name \u201cAustralia\u201d for the continent. Published in Edinburgh the same year Flinders\u2019 own \u201cA Voyage to Terra Australis\u201d appeared, Thomson\u2019s map captured the continent at the dawn of its naming \u2014 the coastline traced from naval surveys, the interior a speculation. New South Wales was the only significant colony; the sites of Melbourne, Adelaide, and Perth were uninhabited. Tasmania was called Van Diemen\u2019s Land. New Guinea appeared hazily to the north. A document of what was known, and how much was not.',
    palette: {
      background: '#f0ebe0',
      fill: ['#b89a6e'],
      stroke: '#6b5030',
      text: '#3a2a10',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-thomson-1814-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_thomson_1814.pmtiles`,
          tileSize: 256,
          maxzoom: 9,
        },
      },
    ],
    layers: [
      {
        id: 'historical-thomson-1814-layer',
        type: 'raster',
        source: 'historical-thomson-1814-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-pinkerton-1818',
    category: 'historical',
    title: 'Pinkerton 1818',
    subtitle: 'Post-Flinders survey of Australasia',
    story: 'John Pinkerton\u2019s 1818 map of Australia and New Zealand, published in his acclaimed \u201cModern Atlas\u201d in London. Just four years after Matthew Flinders completed the first circumnavigation of Australia, Pinkerton incorporated the resulting surveys into one of the first detailed maps to show the continent under its new name. The coastline is now mostly accurate \u2014 Flinders\u2019 painstaking work along the Great Australian Bight, the Gulf of Carpentaria, and the south coast is visible in the detail. The interior remains blank. New Zealand appears to the east, still largely unknown to European science. A transitional map \u2014 the era of guesswork ending, the era of inland exploration yet to begin.',
    palette: {
      background: '#ede8d8',
      fill: ['#a88c60'],
      stroke: '#5c4020',
      text: '#2e1e08',
    },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/landscape/style.json?key=${MT}`,
    sources: [
      {
        id: 'historical-pinkerton-1818-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_pinkerton_1818.pmtiles`,
          tileSize: 256,
          maxzoom: 8,
        },
      },
    ],
    layers: [
      {
        id: 'historical-pinkerton-1818-layer',
        type: 'raster',
        source: 'historical-pinkerton-1818-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-tallis-1851',
    category: 'historical',
    title: 'Tallis 1851',
    subtitle: 'Victorian ornamental map of Australia',
    story: 'John Tallis & Company\u2019s 1851 \u201cExploration Map of Australia\u201d is one of the great showpieces of Victorian cartography. Published during the gold rush era, it frames the continent in elaborate engraved panels depicting Aboriginal Australians, colonial scenes, native fauna, and portraits of explorers. The interior is still largely blank \u2014 Ludwig Leichhardt and Charles Sturt had pushed inland, but Burke and Wills were still a decade away. The coastline is now precisely drawn. Inset maps show King George\u2019s Sound, Port Jackson, and Spencer Gulf in detail. Gold had just been discovered in New South Wales; within months of publication, Victoria would become the richest place on earth.',
    palette: {
      background: '#f5efd8',
      fill: ['#d4b06a'],
      stroke: '#7a5a20',
      text: '#3c2a08',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-tallis-1851-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_tallis_1851.pmtiles`,
          tileSize: 256,
          maxzoom: 8,
        },
      },
    ],
    layers: [
      {
        id: 'historical-tallis-1851-layer',
        type: 'raster',
        source: 'historical-tallis-1851-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-johnson-1862',
    category: 'historical',
    title: 'Johnson 1862',
    subtitle: 'American atlas map of Australia',
    story: 'A. J. Johnson\u2019s 1862 map of Australia, published in New York at the height of the American Civil War. By 1862 the interior of Australia was no longer entirely blank \u2014 Robert Burke and William Wills had crossed the continent from south to north the previous year (and died returning). Stuart\u2019s successful crossing followed in 1862 itself. Johnson\u2019s map was already out of date the moment it was printed: it shows the vast interior still labelled as desert and unexplored wilderness. Queensland had just been declared a separate colony. The goldfields of Victoria were producing staggering wealth. A continent being rapidly known, and rapidly transformed.',
    palette: {
      background: '#f2ece0',
      fill: ['#c09a70'],
      stroke: '#705030',
      text: '#3a2810',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-johnson-1862-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_johnson_1862.pmtiles`,
          tileSize: 256,
          maxzoom: 8,
        },
      },
    ],
    layers: [
      {
        id: 'historical-johnson-1862-layer',
        type: 'raster',
        source: 'historical-johnson-1862-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-mitchell-1864',
    category: 'historical',
    title: 'Mitchell 1864',
    subtitle: 'Philadelphia atlas map of Australasia',
    story: 'Samuel Augustus Mitchell Jr.\u2019s 1864 map of Australia and Polynesia, published in Philadelphia during the American Civil War. Mitchell was one of America\u2019s most prolific commercial cartographers, and his atlas maps reached enormous print runs. This plate shows Australia alongside the Pacific \u2014 New Zealand, Fiji, and the islands of Melanesia and Micronesia charted in varying degrees of accuracy. The Australian interior now shows overland explorer routes: the tracks of Burke, Wills, and Stuart are dimly present. The telegraph line from Adelaide to Darwin \u2014 which would connect Australia to the world in 1872 \u2014 was still years away.',
    palette: {
      background: '#ece8dc',
      fill: ['#b8966a'],
      stroke: '#685030',
      text: '#342010',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-mitchell-1864-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_mitchell_1864.pmtiles`,
          tileSize: 256,
          maxzoom: 8,
        },
      },
    ],
    layers: [
      {
        id: 'historical-mitchell-1864-layer',
        type: 'raster',
        source: 'historical-mitchell-1864-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-stieler-1876',
    category: 'historical',
    title: 'Stieler 1876',
    subtitle: 'Perthes atlas: southeastern Australia',
    story: 'Adolf Stieler\u2019s 1876 map of Southeastern Australia, published by Justus Perthes in Gotha \u2014 the most respected cartographic house in 19th-century Europe. The Perthes/Stieler atlases were celebrated for their scientific precision, and this map shows it: the Murray-Darling river system is drawn with exceptional accuracy, the goldfields of Victoria are marked, and the colonies of New South Wales, Victoria, and South Australia are clearly delineated. Tasmania (Van Diemen\u2019s Land until 1856) appears in the south. The year 1876 was the midpoint of the colonial era \u2014 Queensland was booming, inland settlement was pushing into the Riverina, and the age of the great pastoral runs was at its peak.',
    palette: {
      background: '#ede5d0',
      fill: ['#b8926a'],
      stroke: '#604828',
      text: '#2e1808',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-stieler-1876-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_stieler_1876.pmtiles`,
          tileSize: 256,
          maxzoom: 9,
        },
      },
    ],
    layers: [
      {
        id: 'historical-stieler-1876-layer',
        type: 'raster',
        source: 'historical-stieler-1876-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-wwii-1943',
    category: 'historical',
    title: 'Japanese War Map 1943',
    subtitle: 'WWII Japanese aeronautical chart of Australia',
    story: 'A 1943 Japanese Imperial military aeronautical chart of Australia, produced during the height of the Pacific War. In early 1942, Japanese forces had bombed Darwin, raided Broome and Exmouth, and landed in New Guinea. Australia genuinely feared invasion. This map \u2014 a planning document for a military that was studying the continent as potential conquest \u2014 shows Australia as it looked to Japanese strategic planners: the populated southeast coast, the thin ribbon of settlement along the north, the vast empty interior. The chart includes flight route markings and elevation data critical for aerial navigation. By 1943 the tide was turning at Kokoda and Guadalcanal, but the map captures the moment of maximum threat.',
    palette: {
      background: '#e8e0d0',
      fill: ['#a09070'],
      stroke: '#504030',
      text: '#281808',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-wwii-1943-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_wwii_1943.pmtiles`,
          tileSize: 256,
          maxzoom: 8,
        },
      },
    ],
    layers: [
      {
        id: 'historical-wwii-1943-layer',
        type: 'raster',
        source: 'historical-wwii-1943-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-johnson-1861',
    category: 'historical',
    title: 'Johnson 1861',
    subtitle: 'First edition Johnson atlas map',
    story: 'The first edition of A. J. Johnson & Browning\u2019s map of Australia, published in New York in 1861 \u2014 the same year Robert O\u2019Hara Burke and William John Wills made their fatal attempt to cross the continent from south to north. This first edition plate shows Australia at the very moment of maximum exploration excitement: the interior was being penetrated for the first time, but most of it was still unknown. Queensland had just been separated from New South Wales in 1859. The plate was subsequently updated and revised through 1865 and beyond, but this original 1861 edition captures the raw, half-known continent before the telegraphs and railways began to tame it.',
    palette: {
      background: '#f0ece0',
      fill: ['#c09878'],
      stroke: '#6a4828',
      text: '#32180a',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-johnson-1861-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_johnson_1861.pmtiles`,
          tileSize: 256,
          maxzoom: 8,
        },
      },
    ],
    layers: [
      {
        id: 'historical-johnson-1861-layer',
        type: 'raster',
        source: 'historical-johnson-1861-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-johnson-1870',
    category: 'historical',
    title: 'Johnson 1870',
    subtitle: 'Australia & the East Indies',
    story: 'A. J. Johnson\u2019s 1870 map of Australia, the East Indies, and Southeast Asia, placing the continent in its full regional context \u2014 the Dutch East Indies (present-day Indonesia) to the north, the Philippines and Southeast Asia beyond. By 1870 the overland telegraph line from Adelaide to Darwin was under construction; steam shipping had shrunk the world. The map\u2019s portrait orientation, taller than wide, is unusual for an atlas plate \u2014 a reflection of the vast north-south extent of the region from the Philippines down to Tasmania. The Queensland sugar and cattle industries were expanding rapidly; the great gold rushes of Victoria were winding down.',
    palette: {
      background: '#ece5d5',
      fill: ['#b89060'],
      stroke: '#6a4820',
      text: '#301808',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-johnson-1870-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_johnson_1870.pmtiles`,
          tileSize: 256,
          maxzoom: 8,
        },
      },
    ],
    layers: [
      {
        id: 'historical-johnson-1870-layer',
        type: 'raster',
        source: 'historical-johnson-1870-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  {
    id: 'historical-stanford-1880',
    category: 'historical',
    title: 'Stanford\u2019s Australasia c.1880',
    subtitle: 'Victorian masterwork atlas map',
    story: 'Stanford\u2019s Library Map of Australasia, published by Edward Stanford Ltd. of London in the 1880s, is one of the finest Victorian atlas maps of the region. Stanford was Queen Victoria\u2019s appointed cartographer and publisher of choice for serious geographical work; this map was the definitive English reference for Australasia throughout the late 19th century. It shows Australia and New Zealand in extraordinary detail: the railway lines of the colonial era, the telegraph network, the pastoral districts, the goldfields. Scanned at 20,000\u00d7 pixels wide, this is the highest-resolution historical map of Australia available on the atlas. The original print would have been roughly 60 cm wide.',
    palette: {
      background: '#f0ead8',
      fill: ['#c8a870'],
      stroke: '#7a5828',
      text: '#3c2008',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/positron',
    sources: [
      {
        id: 'historical-stanford-1880-src',
        spec: {
          type: 'raster',
          url: `pmtiles://${R2}/historical_stanford_1880.pmtiles`,
          tileSize: 256,
          maxzoom: 9,
        },
      },
    ],
    layers: [
      {
        id: 'historical-stanford-1880-layer',
        type: 'raster',
        source: 'historical-stanford-1880-src',
        paint: { 'raster-opacity': 1.0 },
      },
    ],
  },

  // ── Base style showcase ────────────────────────────────────────

  {
    id: 'style-liberty',
    category: 'base',
    title: 'Liberty',
    subtitle: 'OpenFreeMap — colourful detail',
    story: 'Liberty is OpenFreeMap\'s full-colour style — rich detail, warm tones, and classic OpenStreetMap character. Roads, parks, water, and land use are all colour-coded. A great general-purpose base for data overlays.',
    palette: {
      background: '#f8f4f0',
      fill: ['#c8b89a','#b8c9a3','#e8a87c','#7eb8d4','#c9a0c8','#f4c47a','#90c9a0','#e8c87a'],
      stroke: '#8a7a6a',
      text: '#3a2a1a',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/liberty',
    sources: [],
    layers: [],
  },
  {
    id: 'style-bright',
    category: 'base',
    title: 'Bright',
    subtitle: 'OpenFreeMap — bold contrast',
    story: 'Bright uses bold, high-contrast colours with strong outlines. Roads pop, water is vivid blue, and land use is clearly delineated. Designed for readability at all zoom levels.',
    palette: {
      background: '#ffffff',
      fill: ['#d4e8f0','#d4f0d4','#f0d4d4','#d4d4f0','#f0e8d4','#d4f0e8','#f0d4e8','#e8f0d4'],
      stroke: '#666666',
      text: '#333333',
    },
    noStateFills: true,
    baseStyle: 'https://tiles.openfreemap.org/styles/bright',
    sources: [],
    layers: [],
  },

  // ── MapTiler styles ───────────────────────────────────────────

  {
    id: 'style-satellite',
    category: 'base',
    title: 'Satellite',
    subtitle: 'MapTiler — true colour imagery',
    story: 'True-colour satellite imagery of Australia. Every pixel is real — captured from orbit and stitched into a seamless map. Zoom in to see individual paddocks, reefs, and urban grids from above.',
    palette: { background: '#0a1628', fill: ['#1a3a5c'], stroke: '#4a8ab5', text: '#e0f0ff' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/satellite/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-hybrid',
    category: 'base',
    title: 'Hybrid',
    subtitle: 'MapTiler — satellite with labels',
    story: 'Satellite imagery overlaid with road networks, place names, and boundaries. The best of both worlds — real-world detail with navigational context.',
    palette: { background: '#0a1628', fill: ['#1a3a5c'], stroke: '#4a8ab5', text: '#e0f0ff' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/hybrid/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-topo',
    category: 'base',
    title: 'Topographic',
    subtitle: 'MapTiler — elevation & terrain',
    story: 'Topographic contours reveal Australia\'s hidden relief — the vast flat interior, the Great Dividing Range, the dramatic gorges of the Kimberley and Flinders Ranges. Land that looks flat on a standard map tells a different story in topo.',
    palette: { background: '#f5f0e8', fill: ['#e8dfc8'], stroke: '#8a7a5a', text: '#3a2a0a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/topo/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-outdoor',
    category: 'base',
    title: 'Outdoor',
    subtitle: 'MapTiler — hiking & nature',
    story: 'Designed for the outdoors — hiking trails, national park boundaries, elevation shading, and natural features take centre stage. The map that walkers, climbers, and adventurers reach for.',
    palette: { background: '#f0efe8', fill: ['#dde8cc'], stroke: '#7a9a5a', text: '#2a3a1a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/outdoor-v2/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-aquarelle',
    category: 'base',
    title: 'Aquarelle',
    subtitle: 'MapTiler — watercolour',
    story: 'Australia rendered as a watercolour painting — soft washes of colour, hand-drawn character, and an artistic warmth that no digital map usually captures. A style unlike any other.',
    palette: { background: '#f8f0e0', fill: ['#e8d8b8'], stroke: '#b8987a', text: '#4a3020' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/aquarelle/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-ocean',
    category: 'base',
    title: 'Ocean',
    subtitle: 'MapTiler — maritime focus',
    story: 'A nautical-inspired style that brings Australia\'s vast ocean territory into focus. The seas, bays, straits, and reefs surrounding the continent are given equal weight to the land.',
    palette: { background: '#0a2040', fill: ['#1a3a5a'], stroke: '#2a6a9a', text: '#c0e0f0' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/ocean/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-winter',
    category: 'base',
    title: 'Winter',
    subtitle: 'MapTiler — cool & crisp',
    story: 'A cool, wintry palette — muted blues, soft whites, and crisp outlines. A style that makes the Australian continent feel otherworldly and serene.',
    palette: { background: '#e8f0f8', fill: ['#d0dde8'], stroke: '#7a9ab8', text: '#1a2a3a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/winter/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-toner',
    category: 'base',
    title: 'Toner',
    subtitle: 'MapTiler — black & white',
    story: 'Stark black and white — every road, river, and coastline reduced to pure ink on paper. A classic newspaper cartography style that strips the map to its bare geometry.',
    palette: { background: '#ffffff', fill: ['#e8e8e8'], stroke: '#000000', text: '#000000' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/toner-v2/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-landscape',
    category: 'base',
    title: 'Landscape',
    subtitle: 'MapTiler — natural terrain',
    story: 'Natural colour terrain shading — green lowlands, brown highlands, grey mountains. Australia\'s geography rendered the way physical geography textbooks used to draw it.',
    palette: { background: '#e8f0d8', fill: ['#d8e8c8'], stroke: '#8a9a6a', text: '#2a3a1a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/landscape/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-dataviz',
    category: 'base',
    title: 'Dataviz',
    subtitle: 'MapTiler — clean data canvas',
    story: 'Designed as a neutral backdrop for data overlays — minimal colour, subdued geography, maximum contrast for your data layers. The cartographer\'s equivalent of graph paper.',
    palette: { background: '#f5f5f5', fill: ['#e0e8e8'], stroke: '#9abaaa', text: '#1a2a2a' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/dataviz/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'style-dataviz-dark',
    category: 'base',
    title: 'Dataviz Dark',
    subtitle: 'MapTiler — dark data canvas',
    story: 'The dark edition of the data visualisation canvas — a near-black base that makes bright data overlays pop with maximum contrast. Ideal for density maps, heat maps, and night-mode dashboards.',
    palette: { background: '#0a1020', fill: ['#1a2535'], stroke: '#2a4a5a', text: '#c0d8e8' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/dataviz-dark/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'backdrop',
    category: 'base',
    title: 'Backdrop',
    subtitle: 'MapTiler — detailed reference map',
    story: 'Backdrop is a clean, detailed reference basemap from MapTiler — designed to support data overlays without competing with them. It combines clear topography, road networks, and place labels on a neutral canvas.',
    palette: { background: '#e8e0d8', fill: ['#d4cfc8'], stroke: '#a09890', text: '#3a3530' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/backdrop/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'topo',
    category: 'base',
    title: 'Topo',
    subtitle: 'MapTiler — topographic map',
    story: 'A classic topographic basemap showing elevation contours, terrain shading, waterways, and land cover. Great for understanding the physical landscape of Australia — from the Great Dividing Range to the flat expanse of the interior.',
    palette: { background: '#f0ede5', fill: ['#e8e0d0'], stroke: '#8a7a60', text: '#3a3020' },
    noStateFills: true,
    baseStyle: `https://api.maptiler.com/maps/topo/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
  {
    id: 'rivers',
    category: 'environment',
    title: 'River Basins',
    subtitle: 'Drainage divisions & waterways',
    story: 'Australia\'s river network mapped by drainage division — 13 basins coloured by watershed, with line weight scaled by upstream drainage area. Data from the Bureau of Meteorology Geofabric V3.3, showing 682,000 stream segments from the full SH_Network dataset.',
    palette: { background: '#0a0a0f', fill: ['#1a2a3a'], stroke: '#4a7a9b', text: '#c8d8e8' },
    noStateFills: true,
    baseStyle: { version: 8, glyphs: `https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key=${MT}`, sources: {}, layers: [{ id: 'bg', type: 'background', paint: { 'background-color': '#0a0a0f' } }] },
    sources: [
      {
        id: 'rivers',
        spec: { type: 'vector', url: `pmtiles://${R2}/rivers.pmtiles` },
      },
    ],
    layers: [
      {
        // Glow layer — wide + blurred underneath for luminous effect
        id: 'rivers-glow',
        type: 'line',
        source: 'rivers',
        'source-layer': 'rivers',
        paint: {
          'line-color': ['get', 'colour'],
          'line-width': [
            'interpolate', ['linear'], ['zoom'],
            3, ['interpolate', ['linear'], ['get', 'w'], 0, 1.5, 1, 6.0],
            8, ['interpolate', ['linear'], ['get', 'w'], 0, 3.0, 1, 12.0],
            12, ['interpolate', ['linear'], ['get', 'w'], 0, 4.0, 1, 18.0],
          ],
          'line-opacity': [
            'interpolate', ['linear'], ['get', 'w'],
            0, 0.08,
            1, 0.25,
          ],
          'line-blur': 4,
        },
      },
      {
        // Core layer — sharp bright lines on top
        id: 'rivers-lines',
        type: 'line',
        source: 'rivers',
        'source-layer': 'rivers',
        paint: {
          'line-color': ['get', 'colour'],
          'line-width': [
            'interpolate', ['linear'], ['zoom'],
            3, ['interpolate', ['linear'], ['get', 'w'], 0, 0.5, 1, 2.5],
            8, ['interpolate', ['linear'], ['get', 'w'], 0, 0.8, 1, 5.0],
            12, ['interpolate', ['linear'], ['get', 'w'], 0, 1.2, 1, 8.0],
          ],
          'line-opacity': [
            'interpolate', ['linear'], ['get', 'w'],
            0, 0.75,
            1, 1.0,
          ],
        },
      },
    ],
  },
  {
    id: 'terrain-3d',
    category: 'base',
    title: '3D Terrain',
    subtitle: 'Interactive elevation — tilt & rotate',
    story: 'Real 3D terrain powered by MapTiler\'s elevation model. Tilt the map with right-click drag (or two-finger drag on trackpad) to explore Australia\'s topography in three dimensions — from the rugged Great Dividing Range to the vast flat interior of the continent.',
    palette: { background: '#c8d8e8', fill: ['#e0ead0'], stroke: '#8a9a80', text: '#2a3020' },
    noStateFills: true,
    terrain: true,
    initialZoom: 5.0,
    baseStyle: `https://api.maptiler.com/maps/outdoor-v2/style.json?key=${MT}`,
    sources: [],
    layers: [],
  },
];

// Default view — Australia centred, all states visible
export const DEFAULT_VIEW = {
  center: [134.0, -27.0],
  zoom: 4.0,
  minZoom: 3.2,
  maxZoom: 14,
  // Bounding box: cannot pan outside Australia + buffer
  maxBounds: [[105, -48], [160, -7]],
};
